# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/hyuk_blog_db
#     username: root
#     password: ENC(CzuAGRkXOyiECqlkyIio0w==)
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     properties:
#       hibernate:
#         jdbc:
#           batch_size: 20
#         order_inserts: true
#         order_updates: true
#         enable_lazy_load_no_trans: true

# # 개발 환경 설정
# logging:
#   level:
#     com.example.hyuk_blog: DEBUG
#     org.springframework.security: DEBUG 