# 서버 포트 설정 (AWS Elastic Beanstalk 환경 변수 사용)
server:
  port: 5000

# AWS RDS Database 설정 (실제 값 사용)
#spring:
#  datasource:
#    url: jdbc:mysql://awseb-e-eipj6ckd2w-stack-awsebrdsdatabase-m0ru059s7ksh.cz86ig6e2h64.ap-northeast-2.rds.amazonaws.com:3306/hyuk_blog_db?useSSL=true&requireSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hyuk_blog_db
    username: root
    password: Shka991204!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        enable_lazy_load_no_trans: true
  # Flyway 설정 (마이그레이션 체크 비활성화)
  #flyway:
  #  enabled: true
  #  baseline-on-migrate: true
  #  out-of-order: true
  #  validate-on-migrate: false
  #  default-schema: hyuk_blog_db
  #  schemas: hyuk_blog_db
  #  table: flyway_schema_history
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    cache: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/
      cache:
        period: 0

# 개인정보 표시 설정 (운영 환경에서는 주소와 전화번호 숨김)
app:
  show:
    address: false
    phone: false 