ALTER TABLE resume ADD COLUMN nameKo VARCHAR(255);
ALTER TABLE resume ADD COLUMN nameJa VARCHAR(255);
ALTER TABLE resume ADD COLUMN addressKo VARCHAR(255);
ALTER TABLE resume ADD COLUMN addressJa VARCHAR(255); 